name: Daily

on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: resources/language_analysis.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: percentage, lines
          plugin_languages_sections: recently-used
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 30
          plugin_languages_recent_days: 32
          plugin_languages_recent_load: 500
      - name: Java or Python Snippet of the Day
        uses: lowlighter/metrics@latest
        with:
          filename: resources/code_snippet.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_code: yes
          plugin_code_languages: java, javascript, python, tex 
          plugin_code_load: 400
          plugin_code_lines: 20
          plugin_code_visibility: public
      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: resources/habits_chart.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits_from: 500
          plugin_habits_days: 32
          plugin_habits_trim: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: America/New_York
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          filename: resources/default_metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
