name: Update README

on:
  schedule:
  - cron: 0 */8 * * *
  workflow_dispatch:

jobs:
  update_readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repsoitory
      uses: actions/checkout@v3
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Script Cache
      uses: actions/cache@v3
      with:
        path: cache
        key: ${{hashFiles('**/*.py')}}-${{github.run_id}}-${{github.run_attempt}}
        restore-keys: |
          ${{hashFiles('**/*.py')}}-${{github.run_id}}-
          ${{hashFiles('**/*.py')}}-
    - name: Install Python Dependencies
      run: pip install -r requirements.txt
    - name: Run Script
      run: python script.py
      env:
        API_TOKEN: ${{secrets.API_TOKEN}}
        WAKA_TOKEN: ${{secrets.WAKA_TOKEN}}
    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update README
        commit_author: Author <actions@github.com>
